apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jupyternotebookinstances.jupyternetes.io
spec:
  scope: Namespaced
  group: jupyternetes.io
  names:
    kind: JupyterNotebookInstance
    plural: jupyternotebookinstances
    singular: jupyternotebookinstance
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                template:
                  description: The template to use for this jupyter instance
                  type: object
                  properties:
                    name:
                      type: string
                      description: Name of the template being referenced
                    namespace:
                      type: string
                      description: Namespace of the template being referenced
                variables:
                  type: object
                  description: A list of variables to apply to the template
                  additionalProperties:
                    type: string
            status:
              type: object
              properties:
                text:
                  type: string
                  default: "Pending"
                pods:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
      
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Template
        type: string
        jsonPath: .spec.template.name

      - name: Status
        type: string
        jsonPath: .status.text
